config/routes.rb
Rails.application.routes.draw do
  resources :bank_accounts
  resources :banks
  resources :payment_mandates
  resources :payment_requests do
    member do 
      get "submit"
    end
  end
  resources :partners
  resources :partner_role_types
  #apipie
  mount Upmin::Engine => '/admin'
  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/controllers/partner_role_types_controller.rb
class PartnerRoleTypesController < ApplicationController
  before_action :set_partner_role_type, only: [:show, :edit, :update, :destroy]

  # GET /partner_role_types
  # GET /partner_role_types.json
  def index
    @partner_role_types = PartnerRoleType.all
  end

  # GET /partner_role_types/1
  # GET /partner_role_types/1.json
  def show
  end

  # GET /partner_role_types/new
  def new
    @partner_role_type = PartnerRoleType.new
  end

  # GET /partner_role_types/1/edit
  def edit
  end

  # POST /partner_role_types
  # POST /partner_role_types.json
  def create
    @partner_role_type = PartnerRoleType.new(partner_role_type_params)

    respond_to do |format|
      if @partner_role_type.save
        format.html { redirect_to @partner_role_type, notice: 'Partner role type was successfully created.' }
        format.json { render :show, status: :created, location: @partner_role_type }
      else
        format.html { render :new }
        format.json { render json: @partner_role_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /partner_role_types/1
  # PATCH/PUT /partner_role_types/1.json
  def update
    respond_to do |format|
      if @partner_role_type.update(partner_role_type_params)
        format.html { redirect_to @partner_role_type, notice: 'Partner role type was successfully updated.' }
        format.json { render :show, status: :ok, location: @partner_role_type }
      else
        format.html { render :edit }
        format.json { render json: @partner_role_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /partner_role_types/1
  # DELETE /partner_role_types/1.json
  def destroy
    @partner_role_type.destroy
    respond_to do |format|
      format.html { redirect_to partner_role_types_url, notice: 'Partner role type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_partner_role_type
      @partner_role_type = PartnerRoleType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def partner_role_type_params
      params.require(:partner_role_type).permit(:code, :name)
    end
end

app/helpers/partner_role_types_helper.rb
module PartnerRoleTypesHelper
end

app/views/partner_role_types/_form.html.erb
<%= simple_form_for(@partner_role_type) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :code %>
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/partner_role_types/edit.html.erb
<h1>Editing Partner Role Type</h1>

<%= render 'form' %>

<%= link_to 'Show', @partner_role_type %> |
<%= link_to 'Back', partner_role_types_path %>

app/views/partner_role_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Partner Role Types</h1>

<table>
  <thead>
    <tr>
      <th>Code</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @partner_role_types.each do |partner_role_type| %>
      <tr>
        <td><%= partner_role_type.code %></td>
        <td><%= partner_role_type.name %></td>
        <td><%= link_to 'Show', partner_role_type %></td>
        <td><%= link_to 'Edit', edit_partner_role_type_path(partner_role_type) %></td>
        <td><%= link_to 'Destroy', partner_role_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Partner role type', new_partner_role_type_path %>

app/views/partner_role_types/new.html.erb
<h1>New Partner Role Type</h1>

<%= render 'form' %>

<%= link_to 'Back', partner_role_types_path %>

app/views/partner_role_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Code:</strong>
  <%= @partner_role_type.code %>
</p>

<p>
  <strong>Name:</strong>
  <%= @partner_role_type.name %>
</p>

<%= link_to 'Edit', edit_partner_role_type_path(@partner_role_type) %> |
<%= link_to 'Back', partner_role_types_path %>