config/routes.rb
Rails.application.routes.draw do
  resources :bank_accounts
  resources :banks
  resources :payment_mandates
  resources :payment_requests do
    member do 
      get "submit"
    end
  end
  resources :partners
  resources :partner_role_types
  #apipie
  mount Upmin::Engine => '/admin'
  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/models/payment_request.rb
# == Schema Information
#
# Table name: payment_requests
#
#  id                 :integer          not null, primary key
#  order_no           :string           not null
#  umrn               :string           not null
#  txn_date           :date             not null
#  file_name          :string
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  amount_total       :decimal(10, 2)
#  status             :string
#  payment_mandate_id :integer
#
# Indexes
#
#  index_payment_requests_on_payment_mandate_id  (payment_mandate_id)
#

class PaymentRequest < ActiveRecord::Base
  belongs_to :payment_mandate

  before_validation :update_mandate_id
  after_create :send_notifications


  def update_mandate_id
    mandate = PaymentMandate.find_by(mandate_no: self.umrn)

    if mandate then
      self.payment_mandate_id = mandate.id
    end

  end

  def submit
    if self.status == 'submitted' then
      #return True
    end

    self.update(status: 'submitted')
    msg = "Payment of #{self.amount_total} Rs  for Order No - #{self.order_no} submitted to bank"
    if self.payment_mandate_id then
      mobile_nos = self.payment_mandate.payer_mobile_no ? self.payment_mandate.payer_mobile_no : '  '
      mobile_nos = self.payment_mandate.payee_mobile_no ? mobile_nos + ',' +  self.payment_mandate.payee_mobile_no : mobile_nos 
      mobile_nos.gsub(' ','') 
      send_sms(mobile_nos,msg)
    end
  end

  def send_notifications
    #if mandate.present?
    if self.payment_mandate_id then 
      mobile_nos = self.payment_mandate.payer_mobile_no
      msg = "Payment of #{amount_total} Rs initiated for Order No - #{order_no}"
      send_sms(mobile_nos,msg)
    end
  end

  def send_sms(mobile_nos, msg)
    p mobile_nos
    msg_gateway = "http://login.smsgatewayhub.com/smsapi/pushsms.aspx"
    userid = "ajaykumar.c"
    password = "984332"

    sms = URI::escape("Hello test sms #{msg}")
    #Promotional SMS
    #url = "http://login.smsgatewayhub.com/smsapi/pushsms.aspx?user=#{userid}&pwd=#{password}&to=#{mobile_nos}&sid=WEBSMS&msg=#{sms}&fl=0" 
   
    #Transactional SMS
    url = "http://login.smsgatewayhub.com/smsapi/pushsms.aspx?user=#{userid}&pwd=#{password}&to=#{mobile_nos}&sid=WEBSMS&msg=#{sms}&fl=0&gwid=2" 
    response = Typhoeus.get(url)
    p response
  end

end

app/controllers/payment_requests_controller.rb
class PaymentRequestsController < ApplicationController
  before_action :set_payment_request, only: [:show, :edit, :update, :destroy]

  # GET /payment_requests
  # GET /payment_requests.json
  def index
    @payment_requests = PaymentRequest.all
  end

  # GET /payment_requests/1
  # GET /payment_requests/1.json
  def show
  end

  # GET /payment_requests/new
  def new
    @payment_request = PaymentRequest.new
  end

  # GET /payment_requests/1/edit
  def edit
  end

  # POST /payment_requests
  # POST /payment_requests.json
  def create
    @payment_request = PaymentRequest.new(payment_request_params)

    respond_to do |format|
      if @payment_request.save
        format.html { redirect_to @payment_request, notice: 'Payment request was successfully created.' }
        format.json { render :show, status: :created, location: @payment_request }
      else
        format.html { render :new }
        format.json { render json: @payment_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payment_requests/1
  # PATCH/PUT /payment_requests/1.json
  def update
    respond_to do |format|
      if @payment_request.update(payment_request_params)
        format.html { redirect_to @payment_request, notice: 'Payment request was successfully updated.' }
        format.json { render :show, status: :ok, location: @payment_request }
      else
        format.html { render :edit }
        format.json { render json: @payment_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payment_requests/1
  # DELETE /payment_requests/1.json
  def destroy
    @payment_request.destroy
    respond_to do |format|
      format.html { redirect_to payment_requests_url, notice: 'Payment request was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  def submit
    @payment_request = PaymentRequest.find(params[:id])
    if @payment_request then
      @payment_request.submit()
    end
    respond_to do |format|
      format.html { redirect_to payment_requests_url, notice: 'Payment request status was successfully updated.' }
      format.json { head :no_content }
    end
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment_request
      @payment_request = PaymentRequest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def payment_request_params
      params.require(:payment_request).permit(:order_no, :umrn, :txn_date, :file_name, :amount_total)
    end
end

app/helpers/payment_requests_helper.rb
module PaymentRequestsHelper
end

app/views/payment_requests/_form.html.erb
<%= simple_form_for(@payment_request) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :order_no %>
    <%= f.input :umrn %>
    <%= f.input :txn_date %>
    <%= f.input :file_name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/payment_requests/edit.html.erb
<h1>Editing Payment Request</h1>

<%= render 'form' %>

<%= link_to 'Show', @payment_request %> |
<%= link_to 'Back', payment_requests_path %>

app/views/payment_requests/index.html.erb
<p id="notice"><%= notice %></p>

<h3>Payment Requests</h3>

<table id="payment-requests-table" class="display">
  <thead>
    <tr>
      <th>Order no</th>
      <th>Amount</th>
      <th>UMRN</th>
      <th>Debit date</th>
      <th>Status</th>
      <th>Mandate Id</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @payment_requests.each do |payment_request| %>
      <tr>
        <td><%= payment_request.order_no %></td>
        <td><%= payment_request.amount_total%></td>
        <td><%= payment_request.umrn %></td>
        <td><%= payment_request.txn_date %></td>
        <td><%= payment_request.status%></td>
        <td><%= payment_request.payment_mandate_id%></td>
        <!--<td><%= link_to 'Show', payment_request %></td>-->
        <td><%= link_to 'Edit', edit_payment_request_path(payment_request) %></td>
        <td><%= link_to "Submit", submit_payment_request_path(payment_request) %></td>

        <!--<td><%= link_to 'Destroy', payment_request, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Payment request', new_payment_request_path %>

app/views/payment_requests/new.html.erb
<h1>New Payment Request</h1>

<%= render 'form' %>

<%= link_to 'Back', payment_requests_path %>

app/views/payment_requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Order no:</strong>
  <%= @payment_request.order_no %>
</p>

<p>
  <strong>Umrn:</strong>
  <%= @payment_request.umrn %>
</p>

<p>
  <strong>Txn date:</strong>
  <%= @payment_request.txn_date %>
</p>

<p>
  <strong>File name:</strong>
  <%= @payment_request.file_name %>
</p>

<%= link_to 'Edit', edit_payment_request_path(@payment_request) %> |
<%= link_to 'Back', payment_requests_path %>