config/routes.rb
Rails.application.routes.draw do
  resources :bank_accounts
  resources :banks
  resources :payment_mandates
  resources :payment_requests do
    member do 
      get "submit"
    end
  end
  resources :partners
  resources :partner_role_types
  #apipie
  mount Upmin::Engine => '/admin'
  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/models/bank_account.rb
# == Schema Information
#
# Table name: bank_accounts
#
#  id            :integer          not null, primary key
#  account_no    :string
#  bank_code1    :string
#  code1_type    :string
#  bank_code2    :string
#  code2_type    :string
#  bank_location :string
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  bank_id       :integer          not null
#  partner_id    :integer          not null
#
# Indexes
#
#  index_bank_accounts_on_bank_id     (bank_id)
#  index_bank_accounts_on_partner_id  (partner_id)
#

class BankAccount < ActiveRecord::Base
  belongs_to :bank
end

app/controllers/bank_accounts_controller.rb
class BankAccountsController < ApplicationController
  before_action :set_bank_account, only: [:show, :edit, :update, :destroy]

  # GET /bank_accounts
  # GET /bank_accounts.json
  def index
    @bank_accounts = BankAccount.all
  end

  # GET /bank_accounts/1
  # GET /bank_accounts/1.json
  def show
  end

  # GET /bank_accounts/new
  def new
    @bank_account = BankAccount.new
  end

  # GET /bank_accounts/1/edit
  def edit
  end

  # POST /bank_accounts
  # POST /bank_accounts.json
  def create
    @bank_account = BankAccount.new(bank_account_params)

    respond_to do |format|
      if @bank_account.save
        format.html { redirect_to @bank_account, notice: 'Bank account was successfully created.' }
        format.json { render :show, status: :created, location: @bank_account }
      else
        format.html { render :new }
        format.json { render json: @bank_account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bank_accounts/1
  # PATCH/PUT /bank_accounts/1.json
  def update
    respond_to do |format|
      if @bank_account.update(bank_account_params)
        format.html { redirect_to @bank_account, notice: 'Bank account was successfully updated.' }
        format.json { render :show, status: :ok, location: @bank_account }
      else
        format.html { render :edit }
        format.json { render json: @bank_account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bank_accounts/1
  # DELETE /bank_accounts/1.json
  def destroy
    @bank_account.destroy
    respond_to do |format|
      format.html { redirect_to bank_accounts_url, notice: 'Bank account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bank_account
      @bank_account = BankAccount.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bank_account_params
      params.require(:bank_account).permit(:account_no, :bank_code1, :code1_type, :bank_code2, :code2_type, :bank_location)
    end
end

app/helpers/bank_accounts_helper.rb
module BankAccountsHelper
end

app/views/bank_accounts/_form.html.erb
<%= simple_form_for(@bank_account) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :account_no %>
    <%= f.input :bank_code1 %>
    <%= f.input :code1_type %>
    <%= f.input :bank_code2 %>
    <%= f.input :code2_type %>
    <%= f.input :bank_location %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/bank_accounts/edit.html.erb
<h1>Editing Bank Account</h1>

<%= render 'form' %>

<%= link_to 'Show', @bank_account %> |
<%= link_to 'Back', bank_accounts_path %>

app/views/bank_accounts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Bank Accounts</h1>

<table>
  <thead>
    <tr>
      <th>Account no</th>
      <th>Bank code1</th>
      <th>Code1 type</th>
      <th>Bank code2</th>
      <th>Code2 type</th>
      <th>Bank location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bank_accounts.each do |bank_account| %>
      <tr>
        <td><%= bank_account.account_no %></td>
        <td><%= bank_account.bank_code1 %></td>
        <td><%= bank_account.code1_type %></td>
        <td><%= bank_account.bank_code2 %></td>
        <td><%= bank_account.code2_type %></td>
        <td><%= bank_account.bank_location %></td>
        <td><%= link_to 'Show', bank_account %></td>
        <td><%= link_to 'Edit', edit_bank_account_path(bank_account) %></td>
        <td><%= link_to 'Destroy', bank_account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bank account', new_bank_account_path %>

app/views/bank_accounts/new.html.erb
<h1>New Bank Account</h1>

<%= render 'form' %>

<%= link_to 'Back', bank_accounts_path %>

app/views/bank_accounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Account no:</strong>
  <%= @bank_account.account_no %>
</p>

<p>
  <strong>Bank code1:</strong>
  <%= @bank_account.bank_code1 %>
</p>

<p>
  <strong>Code1 type:</strong>
  <%= @bank_account.code1_type %>
</p>

<p>
  <strong>Bank code2:</strong>
  <%= @bank_account.bank_code2 %>
</p>

<p>
  <strong>Code2 type:</strong>
  <%= @bank_account.code2_type %>
</p>

<p>
  <strong>Bank location:</strong>
  <%= @bank_account.bank_location %>
</p>

<%= link_to 'Edit', edit_bank_account_path(@bank_account) %> |
<%= link_to 'Back', bank_accounts_path %>